"""Remove OTP column from User model

Revision ID: 0a8ae89dc2c0
Revises: 1794ffdb67b5
Create Date: 2024-09-13 17:59:29.043749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8ae89dc2c0'
down_revision = '1794ffdb67b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.VARCHAR(length=6), nullable=True))

    # ### end Alembic commands ###
