"""empty message

Revision ID: 432130e9ca48
Revises: 2a6960f3e89b
Create Date: 2024-09-14 12:20:43.012595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432130e9ca48'
down_revision = '2a6960f3e89b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_submitted', sa.DateTime(), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_column('date_submitted')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
